import type { Task, DashboardStats, SidebarNavItem, DashboardUser } from "../types/dashboard";

export const sampleTasks: Task[] = [
  {
    id: "1",
    title: "Redesign landing page hero section",
    description: "Update the hero section with new illustrations and CTA copy based on latest A/B test results.",
    priority: "high",
    status: "in-progress",
    assignee: "Sarah Chen",
    assigneeAvatarUrl: "https://i.pravatar.cc/150?u=sarah",
    dueDate: "2026-04-15",
    tags: ["design", "frontend"],
  },
  {
    id: "2",
    title: "Fix authentication token refresh",
    description: "Users are being logged out after 30 minutes. Investigate and fix the token refresh mechanism.",
    priority: "high",
    status: "todo",
    assignee: "Marcus Chen",
    assigneeAvatarUrl: "https://i.pravatar.cc/150?u=marcus",
    dueDate: "2026-04-10",
    tags: ["backend", "bug"],
  },
  {
    id: "3",
    title: "Add unit tests for payment module",
    description: "Write comprehensive unit tests for the Stripe integration, covering edge cases and error handling.",
    priority: "medium",
    status: "in-progress",
    assignee: "Alex Rivera",
    assigneeAvatarUrl: "https://i.pravatar.cc/150?u=alex",
    dueDate: "2026-04-18",
    tags: ["testing", "backend"],
  },
  {
    id: "4",
    title: "Update user onboarding flow",
    description: "Simplify the onboarding wizard to 3 steps based on user feedback surveys.",
    priority: "medium",
    status: "done",
    assignee: "Sarah Chen",
    assigneeAvatarUrl: "https://i.pravatar.cc/150?u=sarah",
    dueDate: "2026-04-08",
    tags: ["ux", "frontend"],
  },
  {
    id: "5",
    title: "Set up CI/CD pipeline for staging",
    description: "Configure GitHub Actions workflow with automated testing, linting, and deployment to staging.",
    priority: "high",
    status: "done",
    assignee: "Jordan Park",
    assigneeAvatarUrl: "https://i.pravatar.cc/150?u=jordan",
    dueDate: "2026-04-05",
    tags: ["devops"],
  },
  {
    id: "6",
    title: "Implement dark mode for dashboard",
    description: "Add dark mode toggle with localStorage persistence and smooth CSS transitions.",
    priority: "low",
    status: "done",
    assignee: "Alex Rivera",
    assigneeAvatarUrl: "https://i.pravatar.cc/150?u=alex",
    dueDate: "2026-04-12",
    tags: ["frontend", "ux"],
  },
  {
    id: "7",
    title: "Migrate database to PostgreSQL 16",
    description: "Plan and execute migration from PostgreSQL 14 to 16 with minimal downtime.",
    priority: "medium",
    status: "todo",
    assignee: "Jordan Park",
    assigneeAvatarUrl: "https://i.pravatar.cc/150?u=jordan",
    dueDate: "2026-04-25",
    tags: ["backend", "devops"],
  },
  {
    id: "8",
    title: "Write API documentation",
    description: "Document all REST endpoints with OpenAPI spec including request/response examples.",
    priority: "low",
    status: "in-progress",
    assignee: "Marcus Chen",
    assigneeAvatarUrl: "https://i.pravatar.cc/150?u=marcus",
    dueDate: "2026-04-20",
    tags: ["docs"],
  },
  {
    id: "9",
    title: "Optimize image loading performance",
    description: "Implement lazy loading and WebP conversion for all product images to improve LCP.",
    priority: "medium",
    status: "todo",
    assignee: "Sarah Chen",
    assigneeAvatarUrl: "https://i.pravatar.cc/150?u=sarah",
    dueDate: "2026-04-11",
    tags: ["performance", "frontend"],
  },
  {
    id: "10",
    title: "Review and update security policies",
    description: "Annual security audit: review access controls, update dependency vulnerabilities, and refresh documentation.",
    priority: "low",
    status: "todo",
    assignee: "Jordan Park",
    assigneeAvatarUrl: "https://i.pravatar.cc/150?u=jordan",
    dueDate: "2026-04-30",
    tags: ["security"],
  },
];

export const sidebarNavItems: SidebarNavItem[] = [
  { id: "dashboard", label: "Dashboard", icon: "dashboard", isActive: true },
  { id: "tasks", label: "Tasks", icon: "tasks" },
  { id: "calendar", label: "Calendar", icon: "calendar" },
  { id: "team", label: "Team", icon: "team" },
  { id: "reports", label: "Reports", icon: "reports" },
  { id: "settings", label: "Settings", icon: "settings" },
];

export const dashboardStats: DashboardStats = {
  totalTasks: 24,
  completed: 12,
  inProgress: 8,
  overdue: 4,
};

export const currentUser: DashboardUser = {
  name: "Jane Cooper",
  email: "jane@gridstore.com",
  avatarUrl: "https://i.pravatar.cc/150?u=janecooper",
  role: "Project Manager",
};
